name: cinder-volume
base: core24
version: "2025.1"
summary: cinder-volume in a snap
description: |
  This snap is a base snap for cinder-volume. It intended to be used
  directly for supported plugins, but can be used a base for other snaps
  that need to include cinder-volume.

grade: stable
confinement: strict

assumes:
- snapd2.73

package-repositories:
  - type: apt
    cloud: epoxy
    priority: always

environment:
  LC_ALL: C
  PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$SNAP/usr/local/bin:$SNAP/usr/local/sbin:$PATH
  PYTHONPATH: $SNAP/lib/python3.12/site-packages:$SNAP/usr/lib/python3/dist-packages

layout:
  /usr/bin/findmnt:
    bind-file: $SNAP/usr/bin/findmnt
  /usr/lib/multipath:
    symlink: $SNAP/lib/multipath
  /etc/ceph:
    bind: $SNAP_COMMON/etc/ceph

apps:
  cinder-volume:
    environment:
      # Standard library components must have priority in module name resolution: https://storyboard.openstack.org/#!/story/2007806
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/lib/python3.12:$SNAP/lib/python3.12/site-packages
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu/ceph
    command: bin/cinder_volume
    daemon: simple
    plugs:
      - network
      - network-bind
      - network-observe
      - mount-observe
      - block-devices
      - system-observe
      - hardware-observe
      - log-observe
      - process-control
      - kernel-module-control
      - nvme-control
      - iscsi-initiator
      - dm-multipath
      - etc-iscsi
      - etc-tgt
      - sys-kernel-config

parts:
  openstack:
    plugin: nil
    stage-packages:
      - python3-cinder
      - cinder-volume
      - sysfsutils
      - python3-rtslib-fb
      - python3-minimal
      - python3-tz
      - ceph-common
      - nfs-common
      - tgt
      - nvmetcli
      - util-linux
      - nvme-cli
      - multipath-tools
      - udev
    override-build: |
      craftctl default
      # purge some dangling symlinks
      rm -rf $CRAFT_PART_INSTALL/usr/lib/python3/dist-packages/netaddr/eui/iab.txt
      rm -rf $CRAFT_PART_INSTALL/usr/lib/python3/dist-packages/netaddr/eui/oui.txt
      # rewrite symlink
      rm -rf $CRAFT_PART_INSTALL/usr/bin/iscsiadm
    override-prime: |
      craftctl default
      target=$CRAFT_PRIME/usr/bin/iscsiadm
      if [ -L "$target" ]; then
        rm -f "$target"
      fi
      ln -s ../sbin/iscsiadm "$target"

  cinder-volume:
    after: [openstack]
    build-snaps: [astral-uv]
    plugin: python
    source: .
    build-packages:
      - git
    python-requirements:
      - requirements.txt
    override-build: |
      uv export --frozen --no-hashes --format=requirements-txt -o requirements.txt
      craftctl default
      cinder-snap-helpers write-hooks

  bin:
    source: bin/
    plugin: dump
    organize:
      "*": usr/bin/

hooks:
  install:
    plugs: [network]
  configure:
    plugs:
      - network
      - network-control
      - firewall-control

plugs:
  etc-iscsi:
    interface: system-files
    write:
      - /etc/iscsi
  etc-tgt:
    interface: system-files
    write:
      - /etc/tgt
  sys-kernel-config:
    interface: system-files
    write:
      - /sys/kernel/config
